language: python
python:
  - "2.7"

before_install:
  - pip install codecov

install:
  - pip install -e git+https://github.com/tonioo/modoboa.git#egg=modoboa
  - pip install -e git+https://github.com/modoboa/modoboa-admin.git#egg=modoboa-admin
  - python setup.py -q develop
  - pip install -q psycopg2

before_script:
  - psql -c 'create database modoboa_test;' -U postgres

script: 
  - cd test_project
  - coverage run --source ../modoboa_radicale manage.py test modoboa_radicale.tests

after_success:
  - codecov